# Generated by Django 6.0 on 2026-01-03 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Âge')),
                ('pregnancies', models.IntegerField(help_text='Nombre de fois enceinte', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Nombre de grossesses')),
                ('glucose', models.FloatField(help_text='Concentration de glucose plasmatique (mg/dL)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='Glucose')),
                ('blood_pressure', models.FloatField(help_text='Pression artérielle diastolique (mm Hg)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='Pression artérielle')),
                ('skin_thickness', models.FloatField(help_text='Épaisseur du pli cutané du triceps (mm)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Épaisseur de la peau')),
                ('insulin', models.FloatField(help_text='Insuline sérique à 2 heures (mu U/ml)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(900)], verbose_name='Insuline')),
                ('bmi', models.FloatField(help_text='Indice de masse corporelle (poids en kg/(taille en m)^2)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)], verbose_name='IMC')),
                ('diabetes_pedigree', models.FloatField(help_text='Fonction de pedigree du diabète', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Fonction de pedigree')),
                ('prediction', models.BooleanField(default=False, verbose_name='Prédiction diabète')),
                ('probability', models.FloatField(default=0.0, verbose_name='Probabilité (%)')),
                ('date_prediction', models.DateTimeField(auto_now_add=True, verbose_name='Date de prédiction')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-date_prediction'],
            },
        ),
    ]
